"""Persistence ports independent from API, analyzers and ORM implementations."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from ..contracts.execution import AnalyzerTask, ExecutionOutcome
from ..contracts.requests import AnalysisRequest, RepositoryRef
from ..contracts.results import AnalysisEnvelope
from .models import AnalysisRecord, AnalysisSummaryProjection, AnalyzerTaskRecord, RepositoryRecord


class PersistencePort(Protocol):
    def register_repository(self, repository: RepositoryRef) -> RepositoryRecord: ...
    def create_analysis(self, request: AnalysisRequest) -> AnalysisRecord: ...
    def get_analysis(self, analysis_id: str) -> AnalysisRecord | None: ...
    def get_analysis_by_idempotency(self, key: str) -> AnalysisRecord | None: ...
    def get_summary(self, analysis_id: str) -> AnalysisSummaryProjection | None: ...
    def commit_envelope(self, envelope: AnalysisEnvelope) -> AnalysisRecord: ...
    def enqueue_task(self, task: AnalyzerTask) -> AnalyzerTaskRecord: ...
    def claim_task(self, *, worker_id: str, now: datetime, lease_seconds: float) -> AnalyzerTaskRecord | None: ...
    def complete_task(self, outcome: ExecutionOutcome, *, worker_id: str) -> AnalyzerTaskRecord: ...
    def renew_task(self, *, task_id: str, worker_id: str, now: datetime, lease_seconds: float) -> bool: ...
    def fail_task(self, task_id: str, *, worker_id: str, retry: bool, error: str, available_at: datetime) -> None: ...


__all__ = ["PersistencePort"]
